import express from "express";
import { query } from "../db.js";
import { requireAuth } from "../middleware/auth.js";
import { requirePermission } from "../middleware/permissions.js";
const router=express.Router();
function delErr(res,error,label){ if(error?.code==="23503") return res.status(409).json({success:false,message:`${label} is already used in transactions. Deactivate it instead of deleting.`,error:error.message,detail:error.detail||null}); return res.status(500).json({success:false,message:`Failed to delete ${label.toLowerCase()}.`,error:error.message,detail:error.detail||null});}
router.get("/",async(req,res)=>{try{const r=await query(`SELECT location_id,location_code,location_name,is_active,created_at FROM app.location ORDER BY location_name;`);res.json({success:true,count:r.rowCount,locations:r.rows,data:r.rows});}catch(e){res.status(500).json({success:false,message:"Failed to load locations.",error:e.message,detail:e.detail||null});}});
router.get("/:locationId",async(req,res)=>{try{const r=await query(`SELECT location_id,location_code,location_name,is_active,created_at FROM app.location WHERE location_id=$1;`,[req.params.locationId]); if(!r.rowCount) return res.status(404).json({success:false,message:"Location not found."}); res.json({success:true,data:r.rows[0],location:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to load location.",error:e.message,detail:e.detail||null});}});
router.post("/",requireAuth,requirePermission("CREATE_SETUP"),async(req,res)=>{try{const b=req.body||{}; if(!b.location_code) return res.status(400).json({success:false,message:"location_code is required."}); if(!b.location_name) return res.status(400).json({success:false,message:"location_name is required."}); const r=await query(`INSERT INTO app.location(location_id,location_code,location_name,is_active,created_at) VALUES(gen_random_uuid(),$1,$2,$3,now()) RETURNING location_id,location_code,location_name,is_active,created_at;`,[String(b.location_code).toUpperCase(),b.location_name,b.is_active??true]); res.status(201).json({success:true,message:"Location created successfully.",data:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to create location.",error:e.message,detail:e.detail||null});}});
router.patch("/:locationId",requireAuth,requirePermission("EDIT_SETUP"),async(req,res)=>{try{const b=req.body||{}; if(!b.location_code||!b.location_name) return res.status(400).json({success:false,message:"location_code and location_name are required."}); const r=await query(`UPDATE app.location SET location_code=$2,location_name=$3,is_active=$4 WHERE location_id=$1 RETURNING location_id,location_code,location_name,is_active,created_at;`,[req.params.locationId,String(b.location_code).toUpperCase(),b.location_name,b.is_active!==false]); if(!r.rowCount) return res.status(404).json({success:false,message:"Location not found."}); res.json({success:true,message:"Location updated successfully.",data:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to update location.",error:e.message,detail:e.detail||null});}});
router.delete("/:locationId",requireAuth,requirePermission("DELETE"),async(req,res)=>{try{const r=await query(`DELETE FROM app.location WHERE location_id=$1 RETURNING location_id,location_code,location_name;`,[req.params.locationId]); if(!r.rowCount) return res.status(404).json({success:false,message:"Location not found."}); res.json({success:true,message:"Location deleted successfully.",data:r.rows[0]});}catch(e){return delErr(res,e,"Location");}});
export default router;
