import express from "express";
import { query } from "../db.js";
import { requireAuth } from "../middleware/auth.js";
import { requirePermission } from "../middleware/permissions.js";
const router=express.Router();
function delErr(res,error,label){ if(error?.code==="23503") return res.status(409).json({success:false,message:`${label} is already used in transactions. Deactivate it instead of deleting.`,error:error.message,detail:error.detail||null}); return res.status(500).json({success:false,message:`Failed to delete ${label.toLowerCase()}.`,error:error.message,detail:error.detail||null});}
router.get("/",async(req,res)=>{try{const params=[];let where=""; if(req.query.type){params.push(String(req.query.type).toUpperCase());where="WHERE UPPER(party_type)=$1";} const r=await query(`SELECT party_id,party_type,party_name,phone,email,tax_id,billing_address,shipping_address,is_active,created_at FROM app.party ${where} ORDER BY party_name;`,params); res.json({success:true,count:r.rowCount,parties:r.rows,data:r.rows});}catch(e){res.status(500).json({success:false,message:"Failed to load parties.",error:e.message,detail:e.detail||null});}});
router.get("/:partyId",async(req,res)=>{try{const r=await query(`SELECT party_id,party_type,party_name,phone,email,tax_id,billing_address,shipping_address,is_active,created_at FROM app.party WHERE party_id=$1;`,[req.params.partyId]); if(!r.rowCount) return res.status(404).json({success:false,message:"Party not found."}); res.json({success:true,data:r.rows[0],party:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to load party.",error:e.message,detail:e.detail||null});}});
router.post("/",requireAuth,requirePermission("CREATE_SETUP"),async(req,res)=>{try{const b=req.body||{}; if(!b.party_type) return res.status(400).json({success:false,message:"party_type is required."}); if(!b.party_name) return res.status(400).json({success:false,message:"party_name is required."}); const r=await query(`INSERT INTO app.party(party_id,party_type,party_name,phone,email,tax_id,billing_address,shipping_address,is_active,created_at) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7,$8,now()) RETURNING party_id,party_type,party_name,phone,email,tax_id,billing_address,shipping_address,is_active,created_at;`,[String(b.party_type).toUpperCase(),b.party_name,b.phone||null,b.email||null,b.tax_id||null,b.billing_address||null,b.shipping_address||null,b.is_active??true]); res.status(201).json({success:true,message:"Party created successfully.",data:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to create party.",error:e.message,detail:e.detail||null});}});
router.patch("/:partyId",requireAuth,requirePermission("EDIT_SETUP"),async(req,res)=>{try{const b=req.body||{}; if(!b.party_type||!b.party_name) return res.status(400).json({success:false,message:"party_type and party_name are required."}); const r=await query(`UPDATE app.party SET party_type=$2,party_name=$3,phone=$4,email=$5,tax_id=$6,billing_address=$7,shipping_address=$8,is_active=$9 WHERE party_id=$1 RETURNING party_id,party_type,party_name,phone,email,tax_id,billing_address,shipping_address,is_active,created_at;`,[req.params.partyId,String(b.party_type).toUpperCase(),b.party_name,b.phone||null,b.email||null,b.tax_id||null,b.billing_address||null,b.shipping_address||null,b.is_active!==false]); if(!r.rowCount) return res.status(404).json({success:false,message:"Party not found."}); res.json({success:true,message:"Party updated successfully.",data:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to update party.",error:e.message,detail:e.detail||null});}});
router.delete("/:partyId",requireAuth,requirePermission("DELETE"),async(req,res)=>{try{const r=await query(`DELETE FROM app.party WHERE party_id=$1 RETURNING party_id,party_name;`,[req.params.partyId]); if(!r.rowCount) return res.status(404).json({success:false,message:"Party not found."}); res.json({success:true,message:"Party deleted successfully.",data:r.rows[0]});}catch(e){return delErr(res,e,"Party");}});
export default router;
