import express from "express";
import { query } from "../db.js";
import { requireAuth } from "../middleware/auth.js";
import { requirePermission } from "../middleware/permissions.js";
const router = express.Router();
function delErr(res,error,label){ if(error?.code==="23503") return res.status(409).json({success:false,message:`${label} is already used in transactions. Deactivate it instead of deleting.`,error:error.message,detail:error.detail||null}); return res.status(500).json({success:false,message:`Failed to delete ${label.toLowerCase()}.`,error:error.message,detail:error.detail||null});}
router.get("/",async(req,res)=>{try{const r=await query(`SELECT product_id,sku,product_name,product_type,uom_code,track_lots,track_expiry,shelf_life_days,is_active,lot_prefix,is_saleable,bottle_volume_l,pieces_per_carton,pack_size_qty,pack_size_uom_code FROM inv.product ORDER BY product_name;`);res.json({success:true,count:r.rowCount,products:r.rows,data:r.rows});}catch(e){res.status(500).json({success:false,message:"Failed to load products.",error:e.message,detail:e.detail||null});}});
router.get("/:productId",async(req,res)=>{try{const r=await query(`SELECT product_id,sku,product_name,product_type,uom_code,track_lots,track_expiry,shelf_life_days,is_active,lot_prefix,is_saleable,bottle_volume_l,pieces_per_carton,pack_size_qty,pack_size_uom_code FROM inv.product WHERE product_id=$1;`,[req.params.productId]); if(!r.rowCount) return res.status(404).json({success:false,message:"Product not found."}); res.json({success:true,data:r.rows[0],product:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to load product.",error:e.message,detail:e.detail||null});}});
router.post("/",requireAuth,requirePermission("CREATE_SETUP"),async(req,res)=>{try{const b=req.body||{}; if(!b.sku) return res.status(400).json({success:false,message:"sku is required."}); if(!b.product_name) return res.status(400).json({success:false,message:"product_name is required."}); if(!b.product_type) return res.status(400).json({success:false,message:"product_type is required."}); if(!b.uom_code) return res.status(400).json({success:false,message:"uom_code is required."}); const r=await query(`INSERT INTO inv.product(product_id,sku,product_name,product_type,uom_code,track_lots,track_expiry,shelf_life_days,is_active,created_at,lot_prefix,is_saleable,bottle_volume_l,pieces_per_carton,pack_size_qty,pack_size_uom_code) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7,$8,now(),$9,$10,$11,$12,$13,$14) RETURNING product_id,sku,product_name,product_type,uom_code,track_lots,track_expiry,shelf_life_days,is_active,created_at,lot_prefix,is_saleable,bottle_volume_l,pieces_per_carton,pack_size_qty,pack_size_uom_code;`,[String(b.sku).toUpperCase(),b.product_name,String(b.product_type).toUpperCase(),String(b.uom_code).toUpperCase(),b.track_lots??true,b.track_expiry??false,b.shelf_life_days||null,b.is_active??true,b.lot_prefix||null,b.is_saleable??true,b.bottle_volume_l||null,b.pieces_per_carton||null,b.pack_size_qty||null,b.pack_size_uom_code||null]); res.status(201).json({success:true,message:"Product created successfully.",data:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to create product.",error:e.message,detail:e.detail||null});}});
router.patch("/:productId",requireAuth,requirePermission("EDIT_SETUP"),async(req,res)=>{try{const b=req.body||{}; if(!b.sku||!b.product_name||!b.product_type||!b.uom_code) return res.status(400).json({success:false,message:"sku, product_name, product_type and uom_code are required."}); const r=await query(`UPDATE inv.product SET sku=$2,product_name=$3,product_type=$4,uom_code=$5,track_lots=$6,track_expiry=$7,shelf_life_days=$8,is_active=$9,lot_prefix=$10,is_saleable=$11,bottle_volume_l=$12,pieces_per_carton=$13,pack_size_qty=$14,pack_size_uom_code=$15 WHERE product_id=$1 RETURNING product_id,sku,product_name,product_type,uom_code,track_lots,track_expiry,shelf_life_days,is_active,lot_prefix,is_saleable,bottle_volume_l,pieces_per_carton,pack_size_qty,pack_size_uom_code;`,[req.params.productId,String(b.sku).toUpperCase(),b.product_name,String(b.product_type).toUpperCase(),String(b.uom_code).toUpperCase(),!!b.track_lots,!!b.track_expiry,b.shelf_life_days||null,b.is_active!==false,b.lot_prefix||null,b.is_saleable!==false,b.bottle_volume_l||null,b.pieces_per_carton||null,b.pack_size_qty||null,b.pack_size_uom_code||null]); if(!r.rowCount) return res.status(404).json({success:false,message:"Product not found."}); res.json({success:true,message:"Product updated successfully.",data:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to update product.",error:e.message,detail:e.detail||null});}});
router.delete("/:productId",requireAuth,requirePermission("DELETE"),async(req,res)=>{try{const r=await query(`DELETE FROM inv.product WHERE product_id=$1 RETURNING product_id,sku,product_name;`,[req.params.productId]); if(!r.rowCount) return res.status(404).json({success:false,message:"Product not found."}); res.json({success:true,message:"Product deleted successfully.",data:r.rows[0]});}catch(e){return delErr(res,e,"Product");}});
export default router;
