import express from "express";
import { query } from "../db.js";
import { requireAuth } from "../middleware/auth.js";
import { requirePermission } from "../middleware/permissions.js";
const router=express.Router();
function delErr(res,error,label){ if(error?.code==="23503") return res.status(409).json({success:false,message:`${label} is already used in transactions. Do not delete it after use.`,error:error.message,detail:error.detail||null}); return res.status(500).json({success:false,message:`Failed to delete ${label.toLowerCase()}.`,error:error.message,detail:error.detail||null});}
router.get("/",async(req,res)=>{try{const r=await query(`SELECT uom_code,uom_name FROM inv.uom ORDER BY uom_code;`);res.json({success:true,count:r.rowCount,uoms:r.rows,data:r.rows});}catch(e){res.status(500).json({success:false,message:"Failed to load units of measure.",error:e.message,detail:e.detail||null});}});
router.get("/:uomCode",async(req,res)=>{try{const r=await query(`SELECT uom_code,uom_name FROM inv.uom WHERE uom_code=$1;`,[String(req.params.uomCode).toUpperCase()]); if(!r.rowCount) return res.status(404).json({success:false,message:"Unit of measure not found."}); res.json({success:true,data:r.rows[0],uom:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to load unit of measure.",error:e.message,detail:e.detail||null});}});
router.post("/",requireAuth,requirePermission("CREATE_SETUP"),async(req,res)=>{try{const b=req.body||{}; if(!b.uom_code) return res.status(400).json({success:false,message:"uom_code is required."}); if(!b.uom_name) return res.status(400).json({success:false,message:"uom_name is required."}); const r=await query(`INSERT INTO inv.uom(uom_code,uom_name) VALUES($1,$2) RETURNING uom_code,uom_name;`,[String(b.uom_code).toUpperCase(),b.uom_name]); res.status(201).json({success:true,message:"Unit of measure created successfully.",data:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to create unit of measure.",error:e.message,detail:e.detail||null});}});
router.patch("/:uomCode",requireAuth,requirePermission("EDIT_SETUP"),async(req,res)=>{try{const b=req.body||{}; if(!b.uom_name) return res.status(400).json({success:false,message:"uom_name is required."}); const r=await query(`UPDATE inv.uom SET uom_name=$2 WHERE uom_code=$1 RETURNING uom_code,uom_name;`,[String(req.params.uomCode).toUpperCase(),b.uom_name]); if(!r.rowCount) return res.status(404).json({success:false,message:"Unit of measure not found."}); res.json({success:true,message:"Unit of measure updated successfully.",data:r.rows[0]});}catch(e){res.status(500).json({success:false,message:"Failed to update unit of measure.",error:e.message,detail:e.detail||null});}});
router.delete("/:uomCode",requireAuth,requirePermission("DELETE"),async(req,res)=>{try{const r=await query(`DELETE FROM inv.uom WHERE uom_code=$1 RETURNING uom_code,uom_name;`,[String(req.params.uomCode).toUpperCase()]); if(!r.rowCount) return res.status(404).json({success:false,message:"Unit of measure not found."}); res.json({success:true,message:"Unit of measure deleted successfully.",data:r.rows[0]});}catch(e){return delErr(res,e,"Unit of measure");}});
export default router;
