import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, RefreshCw } from "lucide-react";
import { getEfrisDocuments, getEfrisMappings, getEfrisPrecheck, getEfrisSettings, internalMockEfrisSubmit, saveEfrisMapping, updateEfrisSettings } from "@/api/client";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export default function Efris() {
  const qc = useQueryClient();
  const settings = useQuery({ queryKey: ["efris-settings"], queryFn: getEfrisSettings });
  const precheck = useQuery({ queryKey: ["efris-precheck"], queryFn: getEfrisPrecheck });
  const mappings = useQuery({ queryKey: ["efris-mappings"], queryFn: getEfrisMappings });
  const documents = useQuery({ queryKey: ["efris-documents"], queryFn: getEfrisDocuments });
  const [tin, setTin] = useState("");
  const [mappingValue, setMappingValue] = useState<Record<string, string>>({});
  const save = useMutation({ mutationFn: updateEfrisSettings, onSuccess: () => { qc.invalidateQueries({ queryKey: ["efris-settings"] }); qc.invalidateQueries({ queryKey: ["efris-precheck"] }); } });
  const map = useMutation({ mutationFn: ({ kind, payload }: { kind: string; payload: any }) => saveEfrisMapping(kind, payload), onSuccess: () => { qc.invalidateQueries({ queryKey: ["efris-mappings"] }); qc.invalidateQueries({ queryKey: ["efris-precheck"] }); } });
  const mock = useMutation({ mutationFn: ({ id, outcome }: { id: string; outcome: string }) => internalMockEfrisSubmit(id, outcome), onSuccess: () => qc.invalidateQueries({ queryKey: ["efris-documents"] }) });
  const config = settings.data?.data || {};
  const checks = precheck.data?.checks || [];
  const products = mappings.data?.products || [];
  const uoms = mappings.data?.uoms || [];
  const taxes = mappings.data?.taxes || [];
  const branches = mappings.data?.branches || [];
  const field = (key: string) => mappingValue[key] || "";
  return <div className="space-y-6">
    <div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">EFRIS Compliance</h1><p className="text-sm text-slate-500">Uganda adapter foundation. Transport is not configured and no URA calls are made.</p></div><Button variant="outline" onClick={() => { settings.refetch(); precheck.refetch(); mappings.refetch(); documents.refetch(); }}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button></div>
    <Alert><AlertTriangle className="h-4 w-4" /><AlertTitle>URA onboarding required</AlertTitle><AlertDescription>Internal mock values are clearly labelled and are not URA FDNs, verification codes, or QR values. Obtain the official system-to-system specification before configuring transport.</AlertDescription></Alert>
    <Card><CardHeader><CardTitle>EFRIS Settings</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><label className="text-sm">Business TIN<Input value={tin || config.tin || ""} onChange={e => setTin(e.target.value)} placeholder="Verified TIN" /></label><label className="text-sm">Environment<select className="mt-1 w-full rounded border p-2" value={config.environment || "NOT_CONFIGURED"} onChange={e => save.mutate({ environment: e.target.value })}><option>NOT_CONFIGURED</option><option>SANDBOX</option><option>PRODUCTION</option></select></label><label className="text-sm">Registration<select className="mt-1 w-full rounded border p-2" value={config.registration_status || "NOT_CONFIGURED"} onChange={e => save.mutate({ registration_status: e.target.value })}><option>NOT_CONFIGURED</option><option>PENDING</option><option>REGISTERED</option><option>SUSPENDED</option></select></label></div><div className="flex flex-wrap gap-2"><Button onClick={() => save.mutate({ tin, system_to_system_enabled: true, credentials_configured: true, transport_configured: false })}>Save metadata</Button><Button variant="outline" disabled={save.isPending || !precheck.data?.ready} onClick={() => save.mutate({ efris_enabled: !config.efris_enabled })}>{config.efris_enabled ? "Disable EFRIS" : "Enable EFRIS"}</Button><Badge variant={config.efris_enabled ? "default" : "outline"}>{config.efris_enabled ? "Enabled" : "Disabled"}</Badge></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Activation precheck</CardTitle></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-2">{checks.map((check: any) => <div key={check.check_code} className={check.is_valid ? "rounded border border-emerald-200 bg-emerald-50 p-2 text-sm" : "rounded border border-amber-200 bg-amber-50 p-2 text-sm"}>{check.is_valid ? <CheckCircle2 className="mr-2 inline h-4 w-4" /> : <AlertTriangle className="mr-2 inline h-4 w-4" />}{check.message}</div>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle>Mappings</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{products.slice(0, 50).map((p: any) => <div key={p.product_id} className="grid gap-2 rounded border p-2 md:grid-cols-[1fr_220px_auto]"><span>{p.sku} — {p.product_name} ({p.uom_code})</span><Input placeholder="Verified commodity code" value={field(p.product_id)} onChange={e => setMappingValue({ ...mappingValue, [p.product_id]: e.target.value })} /><Button size="sm" onClick={() => map.mutate({ kind: "product", payload: { product_id: p.product_id, commodity_code: field(p.product_id), efris_uom_code: p.efris_uom_code || null } })}>Save</Button></div>)}{uoms.map((u: any) => <div key={u.uom_code} className="grid gap-2 rounded border p-2 md:grid-cols-[1fr_220px_auto]"><span>UOM {u.uom_code} — {u.uom_name}</span><Input placeholder="Verified EFRIS UOM" value={field(`uom:${u.uom_code}`)} onChange={e => setMappingValue({ ...mappingValue, [`uom:${u.uom_code}`]: e.target.value })} /><Button size="sm" onClick={() => map.mutate({ kind: "uom", payload: { uom_code: u.uom_code, efris_uom_code: field(`uom:${u.uom_code}`) } })}>Save</Button></div>)}{taxes.map((t: any) => <div key={t.tax_code_id} className="grid gap-2 rounded border p-2 md:grid-cols-[1fr_220px_auto]"><span>Tax {t.code} — {t.treatment}</span><Input placeholder="Verified EFRIS tax category" value={field(`tax:${t.tax_code_id}`)} onChange={e => setMappingValue({ ...mappingValue, [`tax:${t.tax_code_id}`]: e.target.value })} /><Button size="sm" onClick={() => map.mutate({ kind: "tax", payload: { tax_code_id: t.tax_code_id, efris_tax_category_code: field(`tax:${t.tax_code_id}`) } })}>Save</Button></div>)}{branches.map((b: any) => <div key={b.branch_id} className="grid gap-2 rounded border p-2 md:grid-cols-[1fr_220px_auto]"><span>Branch {b.branch_name}</span><Input placeholder="Verified place-of-business code" value={field(`branch:${b.branch_id}`)} onChange={e => setMappingValue({ ...mappingValue, [`branch:${b.branch_id}`]: e.target.value })} /><Button size="sm" onClick={() => map.mutate({ kind: "branch", payload: { branch_id: b.branch_id, efris_place_of_business_code: field(`branch:${b.branch_id}`) } })}>Save</Button></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Fiscal Documents</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Document</th><th className="p-2">Status</th><th className="p-2">FDN</th><th className="p-2">Attempts</th><th className="p-2">Action</th></tr></thead><tbody>{(documents.data?.data || []).map((d: any) => <tr key={d.efris_document_id} className="border-b"><td className="p-2">{d.source_document_number}</td><td className="p-2"><Badge variant="outline">{d.status}</Badge></td><td className="p-2">{d.fdn || "EFRIS Pending"}</td><td className="p-2">{d.attempt_count}</td><td className="p-2">{d.status !== "ACCEPTED" && <Button size="sm" variant="outline" onClick={() => mock.mutate({ id: d.efris_document_id, outcome: "ACCEPT" })}>Internal Mock</Button>}</td></tr>)}</tbody></table></div></CardContent></Card>
  </div>;
}
