import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { approveInternalStockRequest, createInternalStockRequest, getBranches, getInternalStockRequest, getInternalStockRequests, getLocationsForBranch, getProducts, getStockOnHand, submitInternalStockRequest, createStockTransfer } from "@/api/client";
import { useOperatingContext } from "@/lib/operatingContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function InternalStockRequests(){
  const context=useOperatingContext();const qc=useQueryClient();
  const [selectedId,setSelectedId]=useState("");const [productId,setProductId]=useState("");const [qty,setQty]=useState("10");const [priority,setPriority]=useState("NORMAL");const [requestType,setRequestType]=useState("REPLENISHMENT");const [requestingBranchId,setRequestingBranchId]=useState(context.currentBranch?.branch_id||"");const [requestingLocationId,setRequestingLocationId]=useState(context.currentLocation?.location_id||"");const [sourceBranchId,setSourceBranchId]=useState("");const [sourceLocationId,setSourceLocationId]=useState("");const [approvalQty,setApprovalQty]=useState<Record<string,string>>({});
  useEffect(()=>{if(!requestingBranchId&&context.currentBranch?.branch_id)setRequestingBranchId(context.currentBranch.branch_id);if(!requestingLocationId&&context.currentLocation?.location_id)setRequestingLocationId(context.currentLocation.location_id)},[context.currentBranch?.branch_id,context.currentLocation?.location_id,requestingBranchId,requestingLocationId]);
  const list=useQuery({queryKey:["internal-stock-requests",context.currentBranch?.branch_id],queryFn:()=>getInternalStockRequests(context.currentBranch?.branch_id)});
  const detail=useQuery({queryKey:["internal-stock-request",selectedId],queryFn:()=>getInternalStockRequest(selectedId),enabled:Boolean(selectedId)});
  const request=detail.data?.data;
  const effectiveSourceBranchId=sourceBranchId||request?.preferred_source_branch_id||"";
  const effectiveSourceLocationId=sourceLocationId||request?.preferred_source_location_id||"";
  const requestingBranches=useQuery({queryKey:["requesting-branches"],queryFn:()=>getBranches(false,false)});
  const branches=useQuery({queryKey:["request-source-branches"],queryFn:()=>getBranches(false,true)});
  const requestingLocations=useQuery({queryKey:["requesting-locations",requestingBranchId],queryFn:()=>getLocationsForBranch(requestingBranchId),enabled:Boolean(requestingBranchId)});
  const products=useQuery({queryKey:["request-products"],queryFn:getProducts});
  const sourceLocations=useQuery({queryKey:["request-source-locations",effectiveSourceBranchId],queryFn:()=>getLocationsForBranch(effectiveSourceBranchId,true),enabled:Boolean(effectiveSourceBranchId)});
  const sourceStock=useQuery({queryKey:["request-source-stock",effectiveSourceBranchId,effectiveSourceLocationId],queryFn:()=>getStockOnHand({branch_id:effectiveSourceBranchId,location_id:effectiveSourceLocationId}),enabled:Boolean(effectiveSourceBranchId&&effectiveSourceLocationId)});
  const refresh=async()=>{await qc.invalidateQueries({queryKey:["internal-stock-requests"]});await qc.invalidateQueries({queryKey:["internal-stock-request"]});await qc.invalidateQueries({queryKey:["stock-transfers"]});};
  const create=useMutation({mutationFn:()=>createInternalStockRequest({requesting_branch_id:requestingBranchId,requesting_location_id:requestingLocationId,preferred_source_branch_id:sourceBranchId||null,priority,request_type:requestType,lines:[{product_id:productId,requested_qty:Number(qty)}]}),onSuccess:async(r)=>{setSelectedId(r.data.request_id);await refresh();}});
  const submit=useMutation({mutationFn:submitInternalStockRequest,onSuccess:refresh});
  const approve=useMutation({mutationFn:()=>approveInternalStockRequest(selectedId,(detail.data?.data?.lines||[]).map((line:any)=>({request_line_id:line.request_line_id,approved_qty:Number(approvalQty[line.request_line_id]??line.requested_qty)}))),onSuccess:refresh});
  const transfer=useMutation({mutationFn:()=>{
    const stock=sourceStock.data?.data||[];const lines=request.lines.flatMap((line:any)=>{let remaining=Math.max(0,Number(line.approved_qty)-Number(line.supplied_qty));const eligible=stock.filter((item:any)=>item.product_id===line.product_id&&Number(item.qty_on_hand)>0);if(!eligible.length)throw new Error(`No available source stock for ${line.product_name}`);return eligible.map((row:any)=>{const qty=Math.min(remaining,Number(row.qty_on_hand));remaining-=qty;return {product_id:line.product_id,lot_id:row.lot_id,qty,request_line_id:line.request_line_id};}).filter((item:any)=>item.qty>0);});
    if(!lines.length)throw new Error("No approved outstanding quantities are available at the chosen source location.");
    return createStockTransfer({stock_request_id:request.request_id,source_branch_id:effectiveSourceBranchId,source_location_id:effectiveSourceLocationId,destination_branch_id:request.requesting_branch_id,destination_location_id:request.requesting_location_id,lines});
  },onSuccess:refresh});
  const rows=list.data?.data||[];const productRows=products.data?.products||products.data?.data||[];const selectableBranches=branches.data?.branches||[];const requestLineIds=useMemo(()=>new Set((request?.lines||[]).map((line:any)=>line.request_line_id)),[request]);
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Internal Stock Requests</h1><p className="mt-1 text-sm text-slate-500">Internal replenishment moves through approval and transfer. It does not create supplier or finance documents.</p></div>
    <Card><CardHeader><CardTitle>New Internal Stock Request</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4">
      <label className="flex flex-col gap-1 text-sm">Requesting Branch<select className="h-10 rounded-md border px-2" value={requestingBranchId} onChange={e=>{setRequestingBranchId(e.target.value);setRequestingLocationId("")}}><option value="">Select requesting branch</option>{(requestingBranches.data?.branches||[]).map((b:any)=><option key={b.branch_id} value={b.branch_id}>{b.branch_name}</option>)}</select></label>
      <label className="flex flex-col gap-1 text-sm">Receiving Location<select className="h-10 rounded-md border px-2" value={requestingLocationId} onChange={e=>setRequestingLocationId(e.target.value)}><option value="">Select receiving location</option>{(requestingLocations.data?.locations||[]).filter((loc:any)=>loc.is_active!==false&&loc.is_stock_holding).map((loc:any)=><option key={loc.location_id} value={loc.location_id}>{loc.location_name}</option>)}</select></label>
      <select className="h-10 rounded-md border px-2" value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Select product</option>{productRows.map((p:any)=><option key={p.product_id} value={p.product_id}>{p.sku} — {p.product_name}</option>)}</select>
      <input className="h-10 rounded-md border px-3" type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(e.target.value)} aria-label="Requested quantity"/>
      <label className="flex flex-col gap-1 text-sm">Preferred Source Branch<select className="h-10 rounded-md border px-2" value={sourceBranchId} onChange={e=>{setSourceBranchId(e.target.value);setSourceLocationId("")}}><option value="">Any source branch</option>{selectableBranches.filter((b:any)=>b.branch_id!==requestingBranchId).map((b:any)=><option key={b.branch_id} value={b.branch_id}>{b.branch_name}</option>)}</select></label>
      <select className="h-10 rounded-md border px-2" value={priority} onChange={e=>setPriority(e.target.value)}><option value="NORMAL">Normal</option><option value="URGENT">Urgent</option></select>
      <select className="h-10 rounded-md border px-2" value={requestType} onChange={e=>setRequestType(e.target.value)}><option value="REPLENISHMENT">Replenishment</option><option value="EMERGENCY">Emergency</option><option value="CUSTOMER_ORDER">Customer order</option><option value="REBALANCING">Rebalancing</option><option value="OTHER">Other</option></select>
      <Button disabled={!requestingBranchId||!requestingLocationId||!productId||Number(qty)<=0||create.isPending} onClick={()=>create.mutate()}>Create Draft</Button>
      {create.isError&&<p className="text-sm text-red-600 md:col-span-4">{(create.error as Error).message}</p>}
    </CardContent></Card>
    <Card><CardHeader><CardTitle>Request History</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b text-left"><th className="p-2">Request No</th><th className="p-2">Requesting Branch</th><th className="p-2">Receiving Location</th><th className="p-2">Preferred Source</th><th className="p-2">Status</th><th className="p-2">Priority</th><th className="p-2">Requested</th><th className="p-2">Approved</th><th className="p-2">Supplied</th><th className="p-2">Outstanding</th><th className="p-2"></th></tr></thead><tbody>{rows.map((row:any)=><tr key={row.request_id} onClick={()=>setSelectedId(row.request_id)} onDoubleClick={()=>setSelectedId(row.request_id)} className={`cursor-pointer border-b ${selectedId===row.request_id?"bg-slate-50":""}`}><td className="p-2">{row.request_no}</td><td className="p-2">{row.requesting_branch_name}</td><td className="p-2">{row.receiving_location_name}</td><td className="p-2">{row.source_branch_name||"Any source"}</td><td className="p-2">{row.status}</td><td className="p-2">{row.priority}</td><td className="p-2">{row.requested_qty}</td><td className="p-2">{row.approved_qty}</td><td className="p-2">{row.supplied_qty}</td><td className="p-2">{row.outstanding_qty}</td><td className="p-2"><Button size="sm" variant="outline" onClick={e=>{e.stopPropagation();setSelectedId(row.request_id)}}>View</Button></td></tr>)}</tbody></table>{!rows.length&&<p className="py-6 text-center text-slate-500">No stock requests.</p>}</CardContent></Card>
    {request&&<Card><CardHeader><CardTitle>{request.request_no} · {request.status}</CardTitle><div className="grid gap-1 text-sm text-slate-600 md:grid-cols-2"><p><b>Requesting Branch:</b> {request.requesting_branch_name}</p><p><b>Receiving Location:</b> {request.receiving_location_name}</p><p><b>Preferred Source:</b> {request.source_branch_name||"Any source branch"}</p><p><b>Requested By:</b> {request.requested_by_name||"—"}</p></div></CardHeader><CardContent className="space-y-4"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Product</th><th>Requested</th><th>Approved</th><th>Supplied</th><th>Outstanding</th><th>Approval qty</th></tr></thead><tbody>{request.lines.map((line:any)=><tr key={line.request_line_id} className="border-b"><td className="p-2">{line.sku} — {line.product_name}</td><td>{line.requested_qty}</td><td>{line.approved_qty}</td><td>{line.supplied_qty}</td><td>{Number(line.approved_qty)-Number(line.supplied_qty)}</td><td><input disabled={request.status!=="SUBMITTED"} className="w-24 rounded border p-1" type="number" min="0" max={line.requested_qty} step="0.001" value={approvalQty[line.request_line_id]??line.requested_qty} onChange={e=>setApprovalQty({...approvalQty,[line.request_line_id]:e.target.value})} aria-label={`Approve ${line.product_name}`}/></td></tr>)}</tbody></table>
      <div className="flex flex-wrap gap-2">{request.status==="DRAFT"&&<Button disabled={submit.isPending} onClick={()=>submit.mutate(selectedId)}>Submit</Button>}{request.status==="SUBMITTED"&&<Button disabled={approve.isPending||!requestLineIds.size} onClick={()=>approve.mutate()}>Approve quantities</Button>}</div>
      {request.status==="APPROVED"||request.status==="PARTIALLY_SUPPLIED"?<div className="grid gap-3 rounded border p-3 md:grid-cols-3"><select className="h-10 rounded border px-2" value={sourceBranchId||request.preferred_source_branch_id||""} onChange={e=>{setSourceBranchId(e.target.value);setSourceLocationId("")}}><option value="">Choose source branch</option>{selectableBranches.filter((b:any)=>b.branch_id!==request.requesting_branch_id).map((b:any)=><option key={b.branch_id} value={b.branch_id}>{b.branch_name}</option>)}</select><select className="h-10 rounded border px-2" value={sourceLocationId} onChange={e=>setSourceLocationId(e.target.value)}><option value="">Choose authorized source location</option>{(sourceLocations.data?.locations||[]).filter((loc:any)=>loc.is_stock_holding).map((loc:any)=><option key={loc.location_id} value={loc.location_id}>{loc.location_name}</option>)}</select><div className="rounded border bg-slate-50 p-2 text-sm">{effectiveSourceLocationId&&<><div>Source available: {(sourceStock.data?.data||[]).filter((row:any)=>row.product_id&&request.lines.some((line:any)=>line.product_id===row.product_id)).reduce((sum:number,row:any)=>sum+Number(row.qty_on_hand||0),0).toFixed(3)}</div><div>Approved outstanding: {request.lines.reduce((sum:number,line:any)=>sum+Math.max(0,Number(line.approved_qty)-Number(line.supplied_qty)),0).toFixed(3)}</div></>}</div><Button disabled={!effectiveSourceBranchId||!effectiveSourceLocationId||transfer.isPending} onClick={()=>transfer.mutate()}>Create Transfer for Available Quantity</Button><p className="text-xs text-slate-500 md:col-span-3">Eligible stock is read from the selected branch and location only. Multiple eligible lots are split into separate transfer lines; the backend revalidates source branch, lot and quantity before posting.</p>{transfer.isError&&<p className="text-sm text-red-600 md:col-span-3">{(transfer.error as Error).message}</p>}</div>:null}
      {(submit.isError||approve.isError)&&<p className="text-sm text-red-600">{((submit.error||approve.error) as Error)?.message}</p>}
    </CardContent></Card>}
  </div>;
}
