export type RoleCode =
  | "ADMIN"
  | "MANAGER"
  | "PURCHASING"
  | "INVENTORY"
  | "SALES"
  | "FINANCE"
  | "AUDITOR"
  | "VIEWER";

export const ROLE_GROUPS = {
  ALL_USERS: [
    "ADMIN",
    "MANAGER",
    "PURCHASING",
    "INVENTORY",
    "SALES",
    "FINANCE",
    "AUDITOR",
    "VIEWER",
  ],

  ADMIN_ONLY: ["ADMIN"],

  ADMIN_MANAGER: ["ADMIN", "MANAGER"],

  INVENTORY_ACCESS: ["ADMIN", "MANAGER", "INVENTORY"],

  INVENTORY_VIEW_ACCESS: [
    "ADMIN",
    "MANAGER",
    "INVENTORY",
    "PURCHASING",
    "SALES",
    "FINANCE",
    "AUDITOR",
    "VIEWER",
  ],

  PURCHASING_ACCESS: ["ADMIN", "MANAGER", "PURCHASING"],

  SALES_ACCESS: ["ADMIN", "MANAGER", "SALES"],

  FINANCE_ACCESS: ["ADMIN", "MANAGER", "FINANCE", "AUDITOR"],

  FINANCE_EDIT_ACCESS: ["ADMIN", "MANAGER", "FINANCE"],

  POS_ACCESS: ["ADMIN", "MANAGER", "SALES", "FINANCE"],

  JOURNAL_ACCESS: ["ADMIN", "MANAGER", "FINANCE", "AUDITOR"],

  REPORT_ACCESS: [
    "ADMIN",
    "MANAGER",
    "PURCHASING",
    "INVENTORY",
    "SALES",
    "FINANCE",
    "AUDITOR",
    "VIEWER",
  ],

  AUDIT_ACCESS: ["ADMIN", "MANAGER", "AUDITOR", "FINANCE"],

  SETUP_ACCESS: ["ADMIN", "MANAGER"],

  USER_ACCESS: ["ADMIN"],
} as const;

export const ACTION_ROLES = {
  // General
  DELETE: ["ADMIN"],
  VIEW_ONLY: [
    "ADMIN",
    "MANAGER",
    "PURCHASING",
    "INVENTORY",
    "SALES",
    "FINANCE",
    "AUDITOR",
    "VIEWER",
  ],

  VIEW_CUSTOMER_RETURNS: ["ADMIN", "MANAGER", "SALES", "FINANCE", "INVENTORY", "AUDITOR", "VIEWER"],
  POST_CUSTOMER_RETURN: ["ADMIN", "MANAGER", "SALES", "INVENTORY"],
  VOID_CUSTOMER_RETURN: ["ADMIN", "MANAGER"],
  PROCESS_REFUND: ["ADMIN", "MANAGER", "FINANCE"],

  // Users and roles
  CREATE_USER: ["ADMIN"],
  RESET_PASSWORD: ["ADMIN"],
  ASSIGN_ROLE: ["ADMIN"],
  ACTIVATE_USER: ["ADMIN"],
  DEACTIVATE_USER: ["ADMIN"],

  // Setup
  CREATE_SETUP: ["ADMIN", "MANAGER"],
  EDIT_SETUP: ["ADMIN", "MANAGER"],

  // Purchasing / GRN
  CREATE_PURCHASE_ORDER: ["ADMIN", "MANAGER", "PURCHASING"],
  CREATE_GRN: ["ADMIN", "MANAGER", "PURCHASING", "INVENTORY"],
  POST_GRN: ["ADMIN", "MANAGER", "PURCHASING", "INVENTORY"],

  // Cleaning / production
  CREATE_CLEANING_BATCH: ["ADMIN", "MANAGER", "INVENTORY"],
  POST_CLEANING_BATCH: ["ADMIN", "MANAGER", "INVENTORY"],

  // Sales / delivery
  CREATE_SALES_ORDER: ["ADMIN", "MANAGER", "SALES"],
  CREATE_DELIVERY: ["ADMIN", "MANAGER", "SALES", "INVENTORY"],
  POST_DELIVERY: ["ADMIN", "MANAGER", "SALES", "INVENTORY"],

  // AR
  CREATE_AR_INVOICE: ["ADMIN", "MANAGER", "SALES", "FINANCE"],
  CREATE_RECEIPT: ["ADMIN", "MANAGER", "FINANCE"],

  // POS
  VIEW_POS: ["ADMIN", "MANAGER", "SALES", "FINANCE"],
  CREATE_POS_SALE: ["ADMIN", "MANAGER", "SALES", "FINANCE"],
  ENTER_POS_PRICE: ["ADMIN", "MANAGER", "SALES", "FINANCE"],
  OVERRIDE_POS_PRICE: ["ADMIN", "MANAGER", "FINANCE"],
  VOID_POS_SALE: ["ADMIN", "MANAGER", "FINANCE"],

  // AP
  CREATE_AP_INVOICE: ["ADMIN", "MANAGER", "PURCHASING", "FINANCE"],
  CREATE_AP_PAYMENT: ["ADMIN", "MANAGER", "FINANCE"],

  // Expenses / finance
  CREATE_EXPENSE_VOUCHER: ["ADMIN", "MANAGER", "FINANCE"],
  POST_EXPENSE_VOUCHER: ["ADMIN", "MANAGER", "FINANCE"],
  CREATE_JOURNAL: ["ADMIN", "MANAGER", "FINANCE"],

  // Reconciliation
  CREATE_RECONCILIATION: ["ADMIN", "MANAGER", "FINANCE"],
  CONFIRM_RECONCILIATION: ["ADMIN", "MANAGER", "FINANCE"],
  CANCEL_RECONCILIATION: ["ADMIN", "MANAGER", "FINANCE"],

  // Stock count
  CREATE_STOCK_COUNT: ["ADMIN", "MANAGER", "INVENTORY"],
  LOAD_STOCK_COUNT_LINES: ["ADMIN", "MANAGER", "INVENTORY"],
  UPDATE_STOCK_COUNT_LINES: ["ADMIN", "MANAGER", "INVENTORY"],
  POST_STOCK_COUNT: ["ADMIN", "MANAGER", "INVENTORY"],

  // Stock adjustments / damage
  CREATE_STOCK_ADJUSTMENT: ["ADMIN", "MANAGER", "INVENTORY"],
  POST_STOCK_ADJUSTMENT: ["ADMIN", "MANAGER", "INVENTORY"],

  // Backdated transactions (PHASE 4)
  CREATE_BACKDATED_DELIVERY: ["ADMIN", "MANAGER"],
  CREATE_BACKDATED_AR_INVOICE: ["ADMIN", "MANAGER"],
  CREATE_BACKDATED_AR_PAYMENT: ["ADMIN", "MANAGER"],
  CREATE_BACKDATED_AP_INVOICE: ["ADMIN", "MANAGER"],
  CREATE_BACKDATED_AP_PAYMENT: ["ADMIN", "MANAGER"],
  EDIT_BACKDATED_TRANSACTION: ["ADMIN", "MANAGER"],
  VIEW_BACKDATE_AUDIT: ["ADMIN", "MANAGER", "AUDITOR", "FINANCE"],

  // Lot lifecycle (PHASE 4)
  CLOSE_LOT: ["ADMIN", "MANAGER", "INVENTORY"],
} as const;

export function roleList(values: readonly string[]) {
  return [...values];
}
